=== php5185/XML_Fandango_Project/PeraltaPerez/fandango.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Theaters (Theater+)>
<!ELEMENT Theater (Name, Address, TextNumber, Movies)>
<!ATTLIST Theater id CDATA #REQUIRED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT TextNumber (#PCDATA)>
<!ELEMENT Movies (Movie+)>
<!ELEMENT Movie (Title, html, Photo, MPAA, Duration, Age, Schedules, SpecialNote)>
<!ATTLIST Movie movieId CDATA #REQUIRED>

<!ELEMENT Title (#PCDATA)>
<!ELEMENT html (img)>
<!ELEMENT img (#PCDATA)>
<!ATTLIST html xmlns CDATA #REQUIRED>
<!ATTLIST img src CDATA #REQUIRED>


<!ELEMENT Photo (#PCDATA)>
<!ELEMENT MPAA (#PCDATA)>
<!ELEMENT Duration (#PCDATA)>
<!ELEMENT Age (#PCDATA)>
<!ELEMENT Schedules (Schedule+)>
<!ELEMENT Schedule (#PCDATA)>
<!ELEMENT SpecialNote (Note+)>
<!ELEMENT Note (#PCDATA)>

=== php5185/XML_Fandango_Project/PeraltaPerez/fandango.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Theaters SYSTEM "fandango.dtd">
<?xml-stylesheet href="style.css" type="text/css"?>
<Theaters>
    <Theater id="1">
        <Name>Movies 10</Name>
        <Address>2613 West Henrietta Road, Rochester, NY 14623</Address>
        <TextNumber>36346</TextNumber>
        <Movies>
            <Movie movieId="1">
                <Title>The Spy Who Dumped Me</Title>
                <html xmlns="http://www.w3.org/1999/xhtml">
                    <img src="./images/TheSpy.jpg" />                                                  
                </html>
                <Photo>image/TheSpy.jpg</Photo>
                <MPAA>R</MPAA>
                <Duration>1 hr 33 min</Duration>
                <Age></Age>

                <Schedules>
                    <Schedule>7:40p</Schedule>
                </Schedules>

                <SpecialNote>
                    <Note></Note>
                </SpecialNote>
            </Movie>

            <Movie movieId="2">
                <Title>Incredibles 2</Title>
                <html xmlns="http://www.w3.org/1999/xhtml">
                    <img src="./images/incredible.jpg" />                                               
                </html>
                <Photo>image/incredible.jpg</Photo>
                <MPAA>PG</MPAA>
                <Duration>1 hr 50 min</Duration>
                <Age></Age>

                <Schedules>
                    <Schedule>12:00p</Schedule>
                    <Schedule>2:45p</Schedule>
                    <Schedule>5:30p</Schedule>
                    <Schedule>8:15p</Schedule>
                </Schedules>

                <SpecialNote>
                    <Note></Note>
                </SpecialNote>
            </Movie>

            <Movie movieId="3">
                <Title>Ocean's 8</Title>
                <html xmlns="http://www.w3.org/1999/xhtml">
                    <img src="./images/ocean.jpg" />                                               
                </html>
                <Photo>image/ocean.jpg</Photo>
                <MPAA>PG-13</MPAA>
                <Duration>1 hr 50 min</Duration>
                <Age></Age>

                <Schedules>
                    <Schedule>1:30p</Schedule>
                    <Schedule>4:10p</Schedule>
                </Schedules>

                <SpecialNote>
                    <Note></Note>
                </SpecialNote>
            </Movie>
        </Movies>
    </Theater>



    <Theater id="2">
        <Name>Regal Henrietta Stadium 18</Name>
        <Address>525 Marketplace Drive, Rochester, NY 14623</Address>
        <TextNumber>36346</TextNumber>

        <Movies>
            <Movie movieId="1">
                <Title>Farenheit 11/9</Title>
                <html xmlns="http://www.w3.org/1999/xhtml">
                    <img src="./images/farenheit.jpg" />                                               
                </html>
                <Photo>image/farenheit.jpg</Photo>
                <MPAA>R</MPAA>
                <Duration>2 hr 6 min</Duration>
                <Age>New</Age>

                <Schedules>
                    <Schedule>3:10p</Schedule>
                    <Schedule>6:20p</Schedule>
                    <Schedule>9:35p</Schedule>
                </Schedules>

                <SpecialNote>
                    <Note></Note>
                </SpecialNote>
            </Movie>

            <Movie movieId="2">
                <Title>Crazy Rich Asians</Title>
                <html xmlns="http://www.w3.org/1999/xhtml">
                    <img src="./images/crazyAsians.jpg" />                                               
                </html>
                <Photo>image/crazyAsians.jpg</Photo>
                <MPAA>PG-13</MPAA>
                <Duration>2 hr 0 min</Duration>
                <Age></Age>

                <Schedules>
                    <Schedule>1:00p</Schedule>
                    <Schedule>4:00p</Schedule>
                    <Schedule>7:10p</Schedule>
                    <Schedule>10:05p</Schedule>
                </Schedules>

                <SpecialNote>
                    <Note>Closed caption</Note>
                    <Note>Accessibility device available</Note>
                </SpecialNote>
            </Movie>

            <Movie movieId="3">
                <Title>Ant-Man and the Wasp (2018)</Title>
                <html xmlns="http://www.w3.org/1999/xhtml">
                    <img src="./images/antMan.jpg" />                                               
                </html>
                <Photo>image/antMan.jpg</Photo>
                <MPAA>PG-13</MPAA>
                <Duration>1 hr 58 min</Duration>
                <Age></Age>

                <Schedules>
                    <Schedule>6:35p</Schedule>
                    <Schedule>9:30p</Schedule>
                </Schedules>

                <SpecialNote>
                    <Note>Closed caption</Note>
                    <Note>Accessibility device available</Note>
                </SpecialNote>
            </Movie>
        </Movies>
    </Theater>



    <Theater id="3">
        <Name></Name>
        <Address></Address>
        <TextNumber></TextNumber>
        <Movies>
            <Movie movieId="1">
                <Title>Life Itself (2018)</Title>
                <html xmlns="http://www.w3.org/1999/xhtml">
                    <img src="./images/lifeItself.jpg" />                                               
                </html>
                <Photo></Photo>
                <MPAA>R</MPAA>
                <Duration>1 hr 58 min</Duration>
                <Age>New</Age>

                <Schedules>
                    <Schedule>11:10a</Schedule>
                    <Schedule>1:50p</Schedule>
                    <Schedule>4:30p</Schedule>
                    <Schedule>7:20p</Schedule>
                </Schedules>

                <SpecialNote>
                    <Note></Note>
                </SpecialNote>
            </Movie>

            <Movie movieId="2">
                <Title>Crazy Rich Asians</Title>
                <html xmlns="http://www.w3.org/1999/xhtml">
                    <img src="./images/crazyAsians.jpg" />                                               
                </html>
                <Photo></Photo>
                <MPAA>PG-13</MPAA>
                <Duration>2 hr 0 min</Duration>
                <Age></Age>

                <Schedules>
                    <Schedule>11:20p</Schedule>
                    <Schedule>2:00p</Schedule>
                    <Schedule>4:50p</Schedule>
                    <Schedule>7:30p</Schedule>
                </Schedules>

                <SpecialNote>
                    <Note></Note>
                </SpecialNote>
            </Movie>

            <Movie movieId="3">
                <Title>The Bookshop</Title>
                <html xmlns="http://www.w3.org/1999/xhtml">
                    <img src="./images/theBookshop.jpg" />                                               
                </html>
                <Photo></Photo>
                <MPAA>PG</MPAA>
                <Duration>1 hr 53 min</Duration>
                <Age></Age>

                <Schedules>
                    <Schedule>1:00p</Schedule>
                    <Schedule>6:45p</Schedule>
                </Schedules>

                <SpecialNote>
                    <Note></Note>
                </SpecialNote>
            </Movie>
        </Movies>
    </Theater>

</Theaters>
