=== php5185/XML_Fandango_Project/PeraltaPerez2/fandango.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Theaters">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Header" type="xs:string"/>
                <xs:element name="Subtitle" type="xs:string"/>
                
                <xs:element name="Theater" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Address" type="xs:string"/>
                            <xs:element name="TextNumber" type="xs:string"/>

                            <xs:element name="Movies" maxOccurs="unbounded">
                                <xs:complexType>                                    
                                    <xs:sequence>
                                        
                                        <xs:element name="Movie" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Title" type="xs:string"/>
                                                    <xs:element name="MPAA" type="xs:string"/>
                                                    <xs:element name="Duration" type="xs:string"/>
                                                    <xs:element name="Age" type="xs:string"/>
                                                    <!-- <xs:element name="html" type="xs:string"/> -->
                                                    
                                                    <!-- <xs:element name="html">
                                                        <xs:complexType>                                                            
                                                            <xs:sequence>
                                                                <xs:element name="img"/>
                                                            </xs:sequence>
                                                        </xs:complexType>

                                                    </xs:element> -->

                                                    

                                                    <xs:element name="SpecialNote">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Note" type="xs:string" maxOccurs="unbounded"/>
                                                            </xs:sequence>
                                                        </xs:complexType>                                                        
                                                    </xs:element>

                                                    <xs:element name="Schedules">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Schedule" type="xs:string" maxOccurs="unbounded"/>
                                                            </xs:sequence>
                                                        </xs:complexType>                                                        
                                                    </xs:element>

                                                </xs:sequence>
                                                <xs:attribute name="movieId" type="xs:string" use="required" />
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>

                                </xs:complexType>

                            </xs:element>

                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required" />

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== php5185/XML_Fandango_Project/PeraltaPerez2/fandango.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE Theaters SYSTEM "fandango.dtd"> -->
<?xml-stylesheet href="style.css" type="text/css"?>
<Theaters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./fandango.xsd">
    
    <Header>Fandango</Header>
    <Subtitle>Movie Theaters now playing:</Subtitle>
    <Theater id="1">
        <Name>Movies 10</Name>
        <Address>2613 West Henrietta Road, Rochester, NY 14623</Address>
        <TextNumber>Text to FNDGO (36346) from your wireless device to get this theater's showtimes</TextNumber>
        <Movies>
            <Movie movieId="1">
                <Title>The Spy Who Dumped Me</Title>
                <MPAA>(R)</MPAA>
                <Duration>1 hr 33 min</Duration>
                <Age></Age>
                <!-- <html xmlns="http://www.w3.org/1999/xhtml">
                    <img src="./images/TheSpy.jpg" />                                                  
                </html> -->
                
                <SpecialNote>
                    <Note></Note>
                </SpecialNote>
                

                <Schedules>
                    <Schedule>7:40p</Schedule>
                </Schedules>

                
            </Movie>

            <Movie movieId="2">
                <Title>Incredibles 2</Title>
                
                <!-- <Photo>image/incredible.jpg</Photo> -->
                <MPAA>(PG)</MPAA>
                <Duration>1 hr 50 min</Duration>
                <Age></Age>

                <!-- <html >
                    <img src="./images/incredible.jpg" />                                               
                </html> -->

                <SpecialNote>
                    <Note></Note>
                </SpecialNote>

                <Schedules>
                    <Schedule>12:00p</Schedule>
                    <Schedule>2:45p</Schedule>
                    <Schedule>5:30p</Schedule>
                    <Schedule>8:15p</Schedule>
                </Schedules>

                
            </Movie>

            <Movie movieId="3">
                <Title>Ocean's 8</Title>
                
                <!-- <Photo>image/ocean.jpg</Photo> -->
                <MPAA>(PG-13)</MPAA>
                <Duration>1 hr 50 min</Duration>
                <Age></Age>
                <!-- <html >
                    <img src="./images/ocean.jpg" />                                               
                </html> -->

                <SpecialNote>
                    <Note></Note>
                </SpecialNote>

                <Schedules>
                    <Schedule>1:30p</Schedule>
                    <Schedule>4:10p</Schedule>
                </Schedules>

                
            </Movie>
        </Movies>
    </Theater>



    <Theater id="2">
        <Name>Regal Henrietta Stadium 18</Name>
        <Address>525 Marketplace Drive, Rochester, NY 14623</Address>
        <TextNumber>Text to FNDGO (36346) from your wireless device to get this theater's showtimes</TextNumber>

        <Movies>
            <Movie movieId="1">
                <Title>Farenheit 11/9</Title>
                
                <!-- <Photo>image/farenheit.jpg</Photo> -->
                <MPAA>(R)</MPAA>
                <Duration>2 hr 6 min</Duration>
                <Age>New</Age>

                <!-- <html >
                    <img src="./images/farenheit.jpg" />                                               
                </html> -->

                <SpecialNote>
                    <Note></Note>
                </SpecialNote>

                <Schedules>
                    <Schedule>3:10p</Schedule>
                    <Schedule>6:20p</Schedule>
                    <Schedule>9:35p</Schedule>
                </Schedules>

                
            </Movie>

            <Movie movieId="2">
                <Title>Crazy Rich Asians</Title>
                
                <!-- <Photo>image/crazyAsians.jpg</Photo> -->
                <MPAA>(PG-13)</MPAA>
                <Duration>2 hr 0 min</Duration>
                <Age></Age>

                <!-- <html >
                    <img src="./images/crazyAsians.jpg" />                                               
                </html> -->

                <SpecialNote>
                    <Note> ~Closed caption</Note>
                    <Note> ~Accessibility device available</Note>
                </SpecialNote>

                <Schedules>
                    <Schedule>1:00p</Schedule>
                    <Schedule>4:00p</Schedule>
                    <Schedule>7:10p</Schedule>
                    <Schedule>10:05p</Schedule>
                </Schedules>

                
            </Movie>

            <Movie movieId="3">
                <Title>Ant-Man and the Wasp (2018)</Title>
                
                <!-- <Photo>image/antMan.jpg</Photo> -->
                <MPAA>(PG-13)</MPAA>
                <Duration>1 hr 58 min</Duration>
                <Age></Age>

                <!-- <html >
                    <img src="./images/antMan.jpg" />                                               
                </html> -->

                <SpecialNote>
                    <Note> ~Closed caption</Note>
                    <Note> ~Accessibility device available</Note>
                </SpecialNote>

                <Schedules>
                    <Schedule>6:35p</Schedule>
                    <Schedule>9:30p</Schedule>
                </Schedules>

                
            </Movie>
        </Movies>
    </Theater>



    <Theater id="3">
        <Name>Pittsford Cinemas</Name>
        <Address>3349 Monroe Ave., Pittsford Plaza, Rochester, NY 14628</Address>
        <TextNumber>Text to FNDGO (36346) from your wireless device to get this theater's showtimes</TextNumber>
        <Movies>
            <Movie movieId="1">
                <Title>Life Itself (2018)</Title>
                
                <!-- <Photo></Photo> -->
                <MPAA>(R)</MPAA>
                <Duration>1 hr 58 min</Duration>
                <Age>New</Age>

                <!-- <html >
                    <img src="./images/lifeItself.jpg" />                                               
                </html> -->

                <SpecialNote>
                    <Note></Note>
                </SpecialNote>

                <Schedules>
                    <Schedule>11:10a</Schedule>
                    <Schedule>1:50p</Schedule>
                    <Schedule>4:30p</Schedule>
                    <Schedule>7:20p</Schedule>
                </Schedules>

                
            </Movie>

            <Movie movieId="2">
                <Title>Crazy Rich Asians</Title>
                
                <!-- <Photo></Photo> -->
                <MPAA>(PG-13)</MPAA>
                <Duration>2 hr 0 min</Duration>
                <Age></Age>

                <!-- <html >
                    <img src="./images/crazyAsians.jpg" />                                               
                </html> -->

                <SpecialNote>
                    <Note></Note>
                </SpecialNote>

                <Schedules>
                    <Schedule>11:20p</Schedule>
                    <Schedule>2:00p</Schedule>
                    <Schedule>4:50p</Schedule>
                    <Schedule>7:30p</Schedule>
                </Schedules>

                
            </Movie>

            <Movie movieId="3">
                <Title>The Bookshop</Title>
                
                <!-- <Photo></Photo> -->
                <MPAA>(PG)</MPAA>
                <Duration>1 hr 53 min</Duration>
                <Age></Age>

                <!-- <html >
                    <img src="./images/theBookshop.jpg" />                                               
                </html> -->

                <SpecialNote>
                    <Note></Note>
                </SpecialNote>

                <Schedules>
                    <Schedule>1:00p</Schedule>
                    <Schedule>6:45p</Schedule>
                </Schedules>

                
            </Movie>
        </Movies>
    </Theater>

</Theaters>
